name: Deploy on EC2 self-hosted runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/ubuntu/www/ChatApp

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: /home/ubuntu/www/ChatApp

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install Frontend Dependencies
        run: pnpm install
        working-directory: /home/ubuntu/www/ChatApp/frontend

      - name: Build Frontend
        run: pnpm run build
        working-directory: /home/ubuntu/www/ChatApp/frontend

      - name: Install Backend Dependencies
        run: pnpm install
        working-directory: /home/ubuntu/www/ChatApp/backend

      - name: Reload PM2 processes
        run: pm2 reload all

